import { Button } from "@/components/ui/button";
import { motion } from "motion/react";
import { Rocket, Target, Users, Zap, Brain, TrendingUp, ChevronRight, PlayCircle, Star, BadgeCheck, Sword } from "lucide-react";

interface LandingPageProps {
  onStart: () => void;
}

export function LandingPage({ onStart }: LandingPageProps) {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.2 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 30 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.6 } }
  };

  const features = [
    {
      title: "Daily Skill Missions",
      description: "15–20 minute hyper-focused tasks designed for maximum retention and quick growth.",
      icon: Target,
      color: "bg-blue-500/10 text-brand-primary",
      benefit: "Master coding, communication, or aptitude daily."
    },
    {
      title: "Smart Progress Tracking",
      description: "Visualize your growth with detailed analytics, skill heatmaps, and level progression.",
      icon: TrendingUp,
      color: "bg-cyan-500/10 text-brand-accent",
      benefit: "Know exactly where you stand and what's next."
    },
    {
      title: "Future Self Visualization",
      description: "See a 30-day projection of your skills and career outcomes based on your current pace.",
      icon: Zap,
      color: "bg-indigo-500/10 text-indigo-400",
      benefit: "Motivation based on real future outcomes."
    },
    {
      title: "Skill Battles",
      description: "Challenge friends or peers in high-speed quizzes and coding sprints to climb the ranks.",
      icon: Users,
      color: "bg-purple-500/10 text-purple-400",
      benefit: "Learn faster through healthy competition."
    },
    {
      title: "AI Skill Coach",
      description: "Personalized roadmaps and feedback generated by advanced AI based on your performance.",
      icon: Brain,
      color: "bg-rose-500/10 text-rose-400",
      benefit: "Your private tutor available 24/7."
    },
    {
      title: "Streak & Discipline",
      description: "Build ironclad consistency with Duolingo-style streaks and rewarding badges.",
      icon: BadgeCheck,
      color: "bg-emerald-500/10 text-emerald-400",
      benefit: "Gamified habits that stick forever."
    }
  ];

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200">
      {/* Hero Section */}
      <section className="relative pt-20 pb-32 overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-7xl h-full pointer-events-none">
          <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-blue-600/20 rounded-full blur-[120px]" />
          <div className="absolute bottom-0 right-1/4 w-[500px] h-[500px] bg-cyan-600/10 rounded-full blur-[120px]" />
        </div>

        <div className="container mx-auto px-4 relative">
          <motion.div 
            className="max-w-4xl mx-auto text-center"
            variants={containerVariants}
            initial="hidden"
            animate="visible"
          >
            <motion.div
              variants={itemVariants}
              className="inline-flex items-center gap-2 px-4 py-2 bg-blue-500/10 text-brand-primary rounded-full text-sm font-bold mb-8 border border-blue-500/20"
            >
              <Rocket className="w-4 h-4" />
              <span>The Future of Student Growth is Here</span>
            </motion.div>
            
            <motion.h1
              variants={itemVariants}
              className="font-heading text-6xl md:text-8xl font-extrabold text-white leading-[1.1] mb-8 tracking-tighter"
            >
              Consistent. Focused. <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-primary to-brand-accent">
                Skill PRO.
              </span>
            </motion.h1>

            <motion.p
              variants={itemVariants}
              className="text-lg md:text-xl text-slate-400 mb-12 max-w-2xl mx-auto leading-relaxed"
            >
              Master high-income skills in 15 minutes a day. 
              Gamified learning built for the next generation of top performers.
            </motion.p>

            <motion.div
              variants={itemVariants}
              className="flex flex-col sm:flex-row items-center justify-center gap-6"
            >
              <Button size="lg" onClick={onStart} className="w-full sm:w-auto h-16 px-12 text-xl rounded-2xl bg-brand-primary hover:bg-blue-700 shadow-2xl shadow-blue-500/20 font-bold transition-all hover:scale-105 active:scale-95">
                Start My Journey
              </Button>
              <Button size="lg" variant="outline" className="w-full sm:w-auto h-16 px-12 text-xl rounded-2xl border-slate-700 bg-slate-900/50 backdrop-blur-md hover:bg-slate-800 text-white font-bold transition-all hover:scale-105">
                Watch Demo
                <PlayCircle className="ml-2 w-6 h-6 text-brand-accent" />
              </Button>
            </motion.div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 100 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.8, duration: 1, ease: "circOut" }}
            className="mt-24 relative max-w-5xl mx-auto rounded-[32px] border border-slate-800 shadow-[0_0_100px_rgba(37,99,235,0.1)] overflow-hidden bg-slate-900 group"
          >
             <img 
               src="https://picsum.photos/seed/skillpro/1600/900?dark" 
               alt="Skill PRO App Interface" 
               className="w-full object-cover opacity-80 group-hover:scale-105 transition-transform duration-1000"
               referrerPolicy="no-referrer"
             />
             <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-transparent flex items-center justify-center">
                <motion.div
                  whileHover={{ scale: 1.1 }}
                  whileTap={{ scale: 0.9 }}
                >
                  <Button size="icon" className="w-24 h-24 rounded-full bg-brand-primary/20 backdrop-blur-xl text-white border border-white/20 shadow-2xl">
                    <PlayCircle className="w-12 h-12" />
                  </Button>
                </motion.div>
             </div>
          </motion.div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-20 border-y border-slate-900">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-12 text-center">
            {[
              { label: "Active Users", value: "50K+" },
              { label: "Skills Mastered", value: "1.2M+" },
              { label: "Daily Missions", value: "85K" },
              { label: "Avg. Daily Session", value: "18m" },
            ].map((stat, i) => (
              <motion.div 
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
              >
                <div className="text-3xl md:text-4xl font-black text-white mb-2">{stat.value}</div>
                <div className="text-sm font-bold text-slate-500 uppercase tracking-widest">{stat.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-24 relative">
        <div className="container mx-auto px-4">
          <div className="text-center mb-20">
            <h3 className="text-sm font-bold text-brand-accent uppercase tracking-widest mb-4">Core Ecosystem</h3>
            <h2 className="text-4xl md:text-6xl font-heading font-black text-white mb-6">Mastery, Reimagined.</h2>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {features.map((feature, idx) => (
              <motion.div 
                key={idx} 
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.1 }}
                className="group p-8 rounded-3xl border border-slate-800 hover:border-brand-primary transition-all duration-500 bg-slate-900/50 hover:bg-slate-900 shadow-lg"
              >
                <div className={`w-16 h-16 ${feature.color} rounded-2xl flex items-center justify-center mb-8 group-hover:-translate-y-2 transition-transform`}>
                  <feature.icon className="w-8 h-8" />
                </div>
                <h3 className="text-2xl font-bold mb-4 text-white">{feature.title}</h3>
                <p className="text-slate-400 text-sm leading-relaxed mb-8">{feature.description}</p>
                <div className="pt-6 border-t border-slate-800 flex items-center justify-between">
                  <span className="text-xs font-bold text-slate-500 italic">{feature.benefit}</span>
                  <ChevronRight className="w-5 h-5 text-brand-primary opacity-0 group-hover:opacity-100 transition-opacity" />
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Future Self Teaser */}
      <section className="py-24 bg-slate-900 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-brand-primary/10 rounded-full blur-[120px] -mr-64 -mt-64" />
        <div className="container mx-auto px-4 relative">
          <div className="flex flex-col md:flex-row items-center gap-20">
            <motion.div 
              className="flex-1"
              initial={{ opacity: 0, x: -50 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-5xl md:text-7xl font-heading font-black text-white mb-8 leading-tight">
                Meet your <br />
                <span className="text-brand-accent">Future Self.</span>
              </h2>
              <p className="text-xl text-slate-400 mb-12 leading-relaxed max-w-lg">
                Our projection engine models your skill mastery over 60 days. 
                See your trajectory, earn rank projections, and visualize your 
                career outcomes before they happen.
              </p>
              <Button size="lg" onClick={onStart} className="h-16 px-12 text-xl rounded-2xl bg-white text-slate-900 hover:bg-slate-100 font-bold shadow-2xl">
                See Prediction
              </Button>
            </motion.div>
            <div className="flex-1 w-full grid grid-cols-2 gap-4">
               {[
                 { label: "IQ/SQ Mastery", value: "98th", color: "text-brand-accent" },
                 { label: "Global Ranking", value: "Top 1%", color: "text-blue-400" },
                 { label: "Career Match", value: "Lead Eng", color: "text-indigo-400" },
                 { label: "Projected XP", value: "120K+", color: "text-rose-400" },
               ].map((item, i) => (
                 <motion.div 
                   key={i}
                   initial={{ opacity: 0, y: 20 }}
                   whileInView={{ opacity: 1, y: 0 }}
                   viewport={{ once: true }}
                   transition={{ delay: i * 0.1 }}
                   className="p-8 bg-slate-800 rounded-[32px] border border-slate-700 flex flex-col justify-center"
                 >
                   <div className="text-[10px] font-black uppercase text-slate-500 tracking-widest mb-2">{item.label}</div>
                   <div className={`text-3xl font-black ${item.color}`}>{item.value}</div>
                 </motion.div>
               ))}
            </div>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-32 relative text-center">
        <div className="absolute inset-0 bg-brand-primary opacity-5" />
        <div className="container mx-auto px-4 relative">
          <motion.h2 
            className="text-5xl md:text-8xl font-black text-white mb-12 tracking-tighter"
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
          >
            BECOME <span className="text-brand-accent">PRO.</span>
          </motion.h2>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-6">
            <Button size="lg" onClick={onStart} className="h-16 px-12 text-xl rounded-2xl bg-white text-slate-900 hover:bg-slate-100 font-bold w-full sm:w-auto shadow-2xl transition-transform hover:scale-105 active:scale-95">
              Get Started Now
            </Button>
            <Button size="lg" variant="ghost" className="h-16 px-12 text-xl rounded-2xl text-white hover:bg-white/10 font-bold w-full sm:w-auto border border-white/20">
              Build My Streak
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-20 border-t border-slate-900">
        <div className="container mx-auto px-4 flex flex-col md:flex-row justify-between items-center gap-12 text-center md:text-left">
          <div>
            <div className="flex items-center justify-center md:justify-start gap-2 mb-6">
              <div className="w-10 h-10 bg-brand-primary rounded-xl flex items-center justify-center text-white">
                <Rocket className="w-6 h-6" />
              </div>
              <span className="font-heading font-black text-2xl uppercase italic text-white">Skill <span className="text-brand-accent">PRO</span></span>
            </div>
            <p className="text-slate-500 text-sm max-w-xs">Building the next generation of top performers through consistent daily growth.</p>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-12">
            <div className="space-y-4">
              <div className="text-xs font-black text-white uppercase italic tracking-widest mb-6">Product</div>
              <div className="text-sm text-slate-400 hover:text-brand-accent transition-colors cursor-pointer">Roadmaps</div>
              <div className="text-sm text-slate-400 hover:text-brand-accent transition-colors cursor-pointer">Rankings</div>
              <div className="text-sm text-slate-400 hover:text-brand-accent transition-colors cursor-pointer">Future Self</div>
            </div>
            <div className="space-y-4">
              <div className="text-xs font-black text-white uppercase italic tracking-widest mb-6">Company</div>
              <div className="text-sm text-slate-400 hover:text-brand-accent transition-colors cursor-pointer">About</div>
              <div className="text-sm text-slate-400 hover:text-brand-accent transition-colors cursor-pointer">Careers</div>
              <div className="text-sm text-slate-400 hover:text-brand-accent transition-colors cursor-pointer">Contact</div>
            </div>
            <div className="space-y-4">
              <div className="text-xs font-black text-white uppercase italic tracking-widest mb-6">Legal</div>
              <div className="text-sm text-slate-400 hover:text-brand-accent transition-colors cursor-pointer">Privacy</div>
              <div className="text-sm text-slate-400 hover:text-brand-accent transition-colors cursor-pointer">Terms</div>
            </div>
          </div>
        </div>
        <div className="container mx-auto px-4 mt-20 pt-8 border-t border-slate-900 flex justify-between items-center text-xs text-slate-600">
           <span>© 2026 Skill PRO AI. All rights reserved.</span>
           <div className="flex gap-6">
              <Twitter className="w-4 h-4" />
              <Github className="w-4 h-4" />
           </div>
        </div>
      </footer>
    </div>
  );
}

function Twitter(props: any) {
  return <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z"/></svg>;
}

function Github(props: any) {
  return <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.28 1.15-.28 2.35 0 3.5-.73 1.02-1.08 2.25-1 3.5 0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/><path d="M9 18c-4.51 2-5-2-7-2"/></svg>;
}
